'use client';
import {useEffect,useState} from 'react';
export default function Instructor(){
 const [exam,setExam]=useState({name:'Statistics Exam 2',momUrl:'',duration:90,excel:true,calculator:false,webcam:true,mic:false,screen:true,focus:true,sites:['https://www.myopenmath.com','https://www.statkey.org']});const [site,setSite]=useState('');const [saved,setSaved]=useState(false);
 useEffect(()=>{const x=localStorage.getItem('myopenproctor-exam');if(x)try{setExam(JSON.parse(x))}catch{}},[]);
 const patch=x=>{setExam(e=>({...e,...x}));setSaved(false)};
 function save(){localStorage.setItem('myopenproctor-exam',JSON.stringify(exam));setSaved(true)}
 function addSite(){if(!site)return;try{const u=new URL(site);patch({sites:[...exam.sites,u.origin]});setSite('')}catch{alert('Enter a complete URL beginning with https://')}}
 const studentLink=typeof window==='undefined'?'':`${window.location.origin}/MyOpenProctor/student/`;
 return <main><h1>Instructor Exam Setup</h1><div className="notice"><b>MyOpenMath connection:</b> Paste the student-facing MyOpenMath assessment URL below. MyOpenProctor launches the assessment after the proctoring check; MyOpenMath remains the assessment and grading system.</div><section><h2>Exam</h2><label>Exam name<input value={exam.name} onChange={e=>patch({name:e.target.value})}/></label><label>MyOpenMath assessment URL<input placeholder="https://www.myopenmath.com/..." value={exam.momUrl} onChange={e=>patch({momUrl:e.target.value})}/></label><label>Duration (minutes)<input type="number" min="1" value={exam.duration} onChange={e=>patch({duration:Number(e.target.value)})}/></label></section><section><h2>Allowed resources</h2><label className="check"><input type="checkbox" checked={exam.excel} onChange={e=>patch({excel:e.target.checked})}/> Microsoft Excel</label><label className="check"><input type="checkbox" checked={exam.calculator} onChange={e=>patch({calculator:e.target.checked})}/> Calculator application</label><h3>Allowed websites</h3>{exam.sites.map((s,i)=><div className="pill" key={i}>{s}<button onClick={()=>patch({sites:exam.sites.filter((_,j)=>j!==i)})}>Remove</button></div>)}<div className="row"><input placeholder="https://approved-site.edu" value={site} onChange={e=>setSite(e.target.value)}/><button onClick={addSite}>Add website</button></div></section><section><h2>Proctoring requirements</h2>{[['webcam','Require webcam'],['mic','Require microphone'],['screen','Require entire-screen share'],['focus','Log tab/window focus changes']].map(([k,t])=><label className="check" key={k}><input type="checkbox" checked={exam[k]} onChange={e=>patch({[k]:e.target.checked})}/>{t}</label>)}</section><button className="primary" onClick={save}>Save Exam Configuration</button>{saved&&<section><h2>Ready for student testing</h2><p>Configuration saved in this browser. Student test page:</p><p><a href={studentLink}>{studentLink}</a></p><p><b>Important:</b> GitHub Pages cannot securely store shared course configurations. The production version will move these settings to a database and authenticate instructor/student launches through LTI 1.3.</p></section>}</main>}