'use client';
import {useEffect,useRef,useState} from 'react';
export default function Student(){
 const video=useRef(null),camStream=useRef(null),displayStream=useRef(null),startedAt=useRef(null);
 const [exam,setExam]=useState(null),[cam,setCam]=useState(false),[screen,setScreen]=useState(false),[consent,setConsent]=useState(false),[running,setRunning]=useState(false),[events,setEvents]=useState([]),[elapsed,setElapsed]=useState(0);
 const log=(type,msg)=>setEvents(e=>[...e,{time:new Date().toISOString(),type,msg}]);
 useEffect(()=>{const x=localStorage.getItem('myopenproctor-exam');if(x)try{setExam(JSON.parse(x))}catch{}},[]);
 useEffect(()=>{const visibility=()=>{if(running&&document.hidden)log('warning','Exam tab/window lost focus')};const blur=()=>{if(running)log('warning','Browser window lost focus')};document.addEventListener('visibilitychange',visibility);window.addEventListener('blur',blur);return()=>{document.removeEventListener('visibilitychange',visibility);window.removeEventListener('blur',blur)}},[running]);
 useEffect(()=>{if(!running)return;const t=setInterval(()=>setElapsed(Math.floor((Date.now()-startedAt.current)/1000)),1000);return()=>clearInterval(t)},[running]);
 async function camera(){try{camStream.current=await navigator.mediaDevices.getUserMedia({video:true,audio:!!exam?.mic});video.current.srcObject=camStream.current;setCam(true);log('system','Camera'+(exam?.mic?' and microphone':'')+' enabled')}catch(e){log('error','Media permission denied: '+e.message)}}
 async function share(){try{displayStream.current=await navigator.mediaDevices.getDisplayMedia({video:{displaySurface:'monitor'},audio:false});setScreen(true);log('system','Screen sharing enabled');displayStream.current.getVideoTracks()[0].addEventListener('ended',()=>{setScreen(false);log('warning','Screen sharing stopped during session')})}catch(e){log('error','Screen sharing not started: '+e.message)}}
 function start(){startedAt.current=Date.now();setRunning(true);log('session','Proctoring session started')}
 function launch(){if(!exam?.momUrl)return;log('exam','MyOpenMath assessment launched');window.open(exam.momUrl,'_blank','noopener,noreferrer')}
 function stop(){setRunning(false);log('session','Proctoring session ended')}
 function exportLog(){const blob=new Blob([JSON.stringify({exam:exam?.name,started:new Date(startedAt.current).toISOString(),ended:new Date().toISOString(),events},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='myopenproctor-session-log.json';a.click();URL.revokeObjectURL(a.href)}
 const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
 if(!exam)return <main><h1>Student Proctor Session</h1><div className="notice">No exam has been configured in this browser yet. Open Instructor Setup first and save an exam.</div></main>;
 const ready=consent&&(!exam.webcam||cam)&&(!exam.screen||screen);
 return <main><h1>{exam.name}</h1><div className="notice"><b>Privacy:</b> MyOpenProctor logs configured browser events after you start. Camera/screen access requires your explicit browser permission. This static test version does not upload video.</div><section><h2>Allowed resources</h2><ul>{exam.excel&&<li>Microsoft Excel</li>}{exam.calculator&&<li>Calculator application</li>}{exam.sites.map(s=><li key={s}>{s}</li>)}</ul><p>Time limit configured: <b>{exam.duration} minutes</b></p></section><section><h2>1. System check</h2><video ref={video} autoPlay muted playsInline className="video"/><div className="row">{exam.webcam&&<button onClick={camera}>Enable camera{exam.mic?' + microphone':''}</button>}{exam.screen&&<button onClick={share}>Share entire screen</button>}</div><p>{exam.webcam&&<>Camera: <b>{cam?'Ready':'Not ready'}</b> </>}{exam.screen&&<>· Screen: <b>{screen?'Sharing':'Not sharing'}</b></>}</p></section><section><h2>2. Start proctored exam</h2><label className="check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I consent to the stated proctoring checks for this exam.</label>{!running?<button className="primary" disabled={!ready} onClick={start}>Start Proctored Session</button>:<><p><b>SESSION ACTIVE · {fmt(elapsed)}</b></p>{exam.momUrl?<button className="primary" onClick={launch}>Open MyOpenMath Exam</button>:<p>No MyOpenMath URL configured.</p>}<button onClick={stop}>End Session</button></>}</section><section><h2>3. Proctor event log</h2><div className="log">{events.length?events.map((e,i)=><div key={i}>{new Date(e.time).toLocaleTimeString()} [{e.type}] {e.msg}</div>):'No events yet.'}</div><button onClick={exportLog} disabled={!events.length}>Export Session Log</button></section></main>}