'use client';
import {useEffect,useRef,useState} from 'react';
export default function Student(){
 const video=useRef(null),camStream=useRef(null),displayStream=useRef(null),startedAt=useRef(null);
 const [cam,setCam]=useState(false),[screen,setScreen]=useState(false),[consent,setConsent]=useState(false),[running,setRunning]=useState(false),[events,setEvents]=useState([]),[elapsed,setElapsed]=useState(0);
 const log=(type,msg)=>setEvents(e=>[...e,{time:new Date().toISOString(),type,msg}]);
 useEffect(()=>{const visibility=()=>{if(running&&document.hidden)log('warning','Exam tab/window lost focus')};const blur=()=>{if(running)log('warning','Browser window lost focus')};document.addEventListener('visibilitychange',visibility);window.addEventListener('blur',blur);return()=>{document.removeEventListener('visibilitychange',visibility);window.removeEventListener('blur',blur)}},[running]);
 useEffect(()=>{if(!running)return;const t=setInterval(()=>setElapsed(Math.floor((Date.now()-startedAt.current)/1000)),1000);return()=>clearInterval(t)},[running]);
 async function camera(){try{camStream.current=await navigator.mediaDevices.getUserMedia({video:true,audio:true});video.current.srcObject=camStream.current;setCam(true);log('system','Camera and microphone enabled')}catch(e){log('error','Camera/microphone permission denied: '+e.message)}}
 async function share(){try{displayStream.current=await navigator.mediaDevices.getDisplayMedia({video:{displaySurface:'monitor'},audio:false});setScreen(true);log('system','Screen sharing enabled');displayStream.current.getVideoTracks()[0].addEventListener('ended',()=>{setScreen(false);log('warning','Screen sharing stopped during session')})}catch(e){log('error','Screen sharing not started: '+e.message)}}
 function start(){startedAt.current=Date.now();setRunning(true);log('session','Proctoring session started')}
 function stop(){setRunning(false);log('session','Proctoring session ended')}
 function exportLog(){const blob=new Blob([JSON.stringify({started:new Date(startedAt.current).toISOString(),ended:new Date().toISOString(),events},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='myopenproctor-session-log.json';a.click();URL.revokeObjectURL(a.href)}
 const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
 return <main><h1>Student Proctor Session</h1><div className="notice"><b>Privacy:</b> This version monitors browser focus and screen-share continuity only after you explicitly start the session. Camera/screen access always requires browser permission. Video is not uploaded by this static version.</div><section><h2>1. System check</h2><video ref={video} autoPlay muted playsInline className="video"/><div className="row"><button onClick={camera}>Enable camera + microphone</button><button onClick={share}>Share entire screen</button></div><p>Camera: <b>{cam?'Ready':'Not ready'}</b> · Screen: <b>{screen?'Sharing':'Not sharing'}</b></p></section><section><h2>2. Start exam monitoring</h2><label className="check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I consent to the stated proctoring checks for this exam.</label>{!running?<button className="primary" disabled={!consent||!cam||!screen} onClick={start}>Start Proctored Session</button>:<><p><b>SESSION ACTIVE · {fmt(elapsed)}</b></p><button onClick={stop}>End Session</button></>}</section><section><h2>3. Proctor event log</h2><div className="log">{events.length?events.map((e,i)=><div key={i}>{new Date(e.time).toLocaleTimeString()} [{e.type}] {e.msg}</div>):'No events yet.'}</div><button onClick={exportLog} disabled={!events.length}>Export Session Log</button></section></main>}