const views=[...document.querySelectorAll('.view')];document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));function show(id){views.forEach(v=>v.classList.toggle('active',v.id===id));scrollTo(0,0)}
let exams=[{name:'Statistics Exam 2',code:'STAT-82KQ',time:90,apps:['Excel'],docs:['Formula Sheet.pdf'],status:'Published'},{name:'College Algebra Exam 1',code:'ALG-41MX',time:75,apps:['Calculator'],docs:['Reference Sheet.pdf'],status:'Draft'}];
function render(){examCount.textContent=exams.length;examList.innerHTML=exams.map((e,i)=>`<article class="card"><div class="cardTop"><span class="pill ${e.status==='Published'?'green':'blue'}">${e.status}</span><span class="code">${e.code}</span></div><h2>${e.name}</h2><p>${e.time} minutes · ${e.apps.join(', ')||'No external apps'}</p><div class="chips">${e.docs.map(d=>`<span>${d}</span>`).join('')}</div><div class="actions"><button class="primary" onclick="previewExam(${i})">Student Preview</button><button class="secondary" onclick="editExam(${i})">Edit</button></div></article>`).join('')}
render();newExam.onclick=()=>{examForm.reset();duration.value=90;accessCode.value='MOP-'+Math.random().toString(36).slice(2,6).toUpperCase();examDialog.showModal()};
function saveExam(){if(!examName.value.trim())return alert('Enter an exam name.');exams.push({name:examName.value.trim(),code:accessCode.value.trim()||'MOP-TEST',time:+duration.value||90,apps:excel.checked?['Excel']:[],docs:['Uploaded exam resource'],status:'Draft'});render();examDialog.close()}
function editExam(i){alert('Preview build: Edit controls will connect to the backend exam record.\n\nSelected: '+exams[i].name)}
function previewExam(i){document.querySelector('#student h1').textContent=exams[i].name;document.querySelector('.codeBox b').textContent=exams[i].code;show('student')}
let interval,seconds=0;function startDemo(){document.querySelector('#session').classList.remove('hidden');seconds=0;clearInterval(interval);interval=setInterval(()=>{seconds++;timer.textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0')},1000)}function endDemo(){clearInterval(interval);document.querySelector('#session').classList.add('hidden');alert('Preview session ended. In production, the session and its objective event log are saved for instructor review.')}
function openReview(name){reviewName.textContent=name+' — Session Review';reviewDialog.showModal()}
